service: propeller-web
image: ghcr.io/turbo-puffin/propeller

servers:
  web:
    - 18.118.109.39

proxy:
  ssl: true
  host: propeller.rocks

registry:
  server: ghcr.io
  username: meetclawdius
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

ssh:
  user: ec2-user

builder:
  arch: amd64

asset_path: /rails/public/assets
